### ISSUE TITLE
Distinct sound for keys

### ISSUE THREAD

**Issue by orhun** [orhun/daktilo#24]
**Is your feature request related to a problem? Please describe.**

For the default preset, having a distinct sound for each key press would be an interesting feature. Maybe it might even sound more realistic.

**Describe the solution you'd like**

n/a
Ideas welcome.

**Describe alternatives you've considered**

n/a

**Additional context**

https://www.reddit.com/r/linux/comments/16xu9ek/comment/k37m3qj/?utm_source=share&utm_medium=web2x&context=3

**Comment by Xenira** [comment]
While I like this idea and this seems to be more of a fun project I think it is worth to consider the security implications of this.

With this active it would be possible to figure out passwords (and other inputs) based on the sounds played.

**Comment by orhun** [comment]
Yup, you are definitely right.

> For more realism it might be possible to randomly alter pitch and speed by a little bit.

Sounds good! Are you interested in raising a PR? 🐻

**Comment by Xenira** [comment]
I will try, but not sure how to do this yet. Haven't done any sound processing in rust yet.

**Comment by orhun** [comment]
Got it, let me know when you have progress! I can hop in to help if needed.

**Comment by Xenira** [comment]
Sure, Ill create a draft for config/cli interface first and then see how well I can manage the rest.

**Comment by Xenira** [comment]
Got volume and speed running without much of a problem. There seems to be no option for pitch though.

Any feedback on what I've got so far would be appreciated.

Will do docu and cleanup once everything else is in place.

**Comment by orhun** [comment]
Thanks! Do you think we can use an external library for changing the pitch? Maybe process the audio at runtime before feeding it into the sink?

**Comment by Xenira** [comment]
Guess that is highly dependent on the audio formats we want to support.

**Comment by orhun** [comment]
I think we're only supporting MP3 for now. I will look into if possible to do so.

**Comment by Xenira** [comment]
After some research I think it might not be worth the effort to add the pitch shift option. In fact the speed option should already modify the pitch. Time independent pitch shifting seems to be a little more on the [complex side](http://blogs.zynaptiq.com/bernsee/time-pitch-overview/).

There are no big libraries (as far as I could tell) that implement those algorithms.

My proposal would be to either

1. Drop pitch entirely
2. Create mp3's that are already pitch shifted and add them to the preset

**Comment by Xenira** [comment]
Removed pitch (https://github.com/orhun/daktilo/pull/44#issuecomment-1765139446)
