### ISSUE TITLE
Virustotal found trojan in daktilo-x86_64-pc-windows-msvc.zip

### ISSUE THREAD

**Issue by 4uku** [orhun/daktilo#26]
I decided to check the zip file _daktilo-x86_64-pc-windows-msvc.zip_ on the [**Virustotal**](https://www.virustotal.com) service. Found a Trojan in the files. 
Popular threat label
- trojan.xegumumune

Threat categories
- trojan

Family labels
- xegumumune

Kaspersky - Trojan-Spy.Win64.Xegumumune.lx
ZoneAlarm by Check Point - Trojan-Spy.Win64.Xegumumune.lx

Details: https://www.virustotal.com/gui/file/898dd117df213511c423f003d8575b743fe92f08f8354b89ee427af4c5d8f76c/detection

**Comment by orhun** [comment]
The windows binaries are built in the CI via [`cargo-dist`](https://github.com/axodotdev/cargo-dist), see [`release.yml`](https://github.com/orhun/daktilo/blob/main/.github/workflows/release.yml).

Unfortunately I have no idea about the VirusTotal result or if this is actionable.

**Comment by arda-guler** [comment]
The commonality is that xegumumune seems to be a keylogger, and daktilo also is a program that reads keypresses. That being said, the VirusTotal result is not bad otherwise. (2 alleged detections from 63 security vendors)
