### ISSUE TITLE
Considerations for latency 

### ISSUE THREAD

**Issue by richdrummer33** [orhun/daktilo#29]
Firstly, thanks! 

This tool has increased my programming proficiency by 10% 😉😉😄 
Ps. Lower latency would *for sure* boost this to, like, 15% 😁

Have you considered lower level libs for handling playback? I made some GPT-4 queries about that and here's what I was able to come up with:
https://chat.openai.com/share/d1a243c7-05cf-43a8-b6ef-a1a46bfca668

I haven't worked with low-level audio libraries before, but it seems promising - if that interests you!

Best,
-Rich

**Comment by orhun** [comment]
Thanks for your suggestion and comments! 🐻 I think `rodio` is arguably one of the best audio playback libraries for Rust out there so I'm not planning to switch to a new library anytime soon.

**Comment by richdrummer33** [comment]
That makes sense! I think the latency I perceived is actually due to the keystroke and not software latency (the keypress registers input halfway in the keystroke).
