### ISSUE TITLE
Document why MacOS permissions are needed / look into creating a standalone app

### ISSUE THREAD

**Issue by orhun** [orhun/daktilo#3]
**Is your feature request related to a problem? Please describe.**

> Mac is like "android" and iphone when it comes to permissions. You need to enable input monitoring for the app. 
However, it's unsecure to allow your terminal to monitor for your input, because you can have key loggers hidden in other binaries you run.

![image](https://github.com/orhun/daktilo/assets/24392180/58c27d72-580a-464d-9439-a6a8d4ccdd1b)

**Describe the solution you'd like**

> So one thing we can do is to document why this permission is required. Another thing would be to create a standalone app (similar to the others I have in my screenshot, e.g. discord), so that I can give input monitoring permission only to daktilo.

**Describe alternatives you've considered**

None.

**Additional context**

cc @marcoIeni

**Comment by ivanglushko** [comment]
I gave permission and ran it in terminal still no sound am i doing something wrong?
<img width="500" alt="Screenshot 2023-10-04 at 22 43 01" src="https://github.com/orhun/daktilo/assets/36343782/ce416d14-8049-4b29-8070-5245ab870a56">

**Comment by MarcoIeni** [comment]
I gave permission to the terminal itself (alacritty) and it worked

**Comment by ivanglushko** [comment]
> I gave permission to the terminal itself (alacritty) and it worked

True worked for me as well thanks! I guess it depends on terminal hence the process was started there

**Comment by orhun** [comment]
We should probably document how to do that for MacOS users. Is someone interested in contributing some docs? 🐻

**Comment by nicholasxjy** [comment]
> The process running the blocking listen function (loop) needs to be the parent process (no fork before). The process needs to be granted access to the Accessibility API (i.e. if you're running your process inside Terminal.app, then Terminal.app needs to be added in System Preferences > Security & Privacy > Privacy > Accessibility) If the process is not granted access to the Accessibility API, macOS will silently ignore rdev's listen callback and will not trigger it with events. No error will be generated.

[https://github.com/Narsil/rdev#macos](https://github.com/Narsil/rdev#macos)
