### ISSUE TITLE
Incomplete readme.md

### ISSUE THREAD

**Issue by Jefferydo** [orhun/daktilo#30]
The readme falls down here, leaving the user guessing:

**Installation**
**Cargo**
**daktilo** can be installed from [crates.io](https://crates.io/crates/daktilo)
     cargo install daktilo
The minimum supported Rust version is 1.70.0.

* * * *
Cargo is never defined and there's no link to the app.
The link to install daktilo, crates.io, targets itself (the current page).
Rust is never defined and there's no link to the app.
 
Every potential user unfamiliar with these apps has to investigate them.

**Comment by orhun** [comment]
Hello, thanks for reporting this. 🐻

I pushed 91c8e94567b942a37c32d21e141aa5d337c837fa which gives some information about Rust/Cargo.

Let me know if you have any other ideas about how to improve the documentation. Feel free to [contribute](https://github.com/orhun/daktilo/blob/main/CONTRIBUTING.md) if you are interested!
