### ISSUE TITLE
Sound output doesn't switch to a newly selected audio device in Windows

### ISSUE THREAD

**Issue by DrXadium** [orhun/daktilo#32]
**Describe the bug**

Daktilo does not redirect its sound output to the new default output device on windows if that is changed while the program is running. 

(So if I switch to using my headphones for output, playback continues on the external speakers)

**To reproduce**

1. Download [daktilo-x86_64-pc-windows-msvc.zip](https://github.com/orhun/daktilo/releases/download/v0.2.0/daktilo-x86_64-pc-windows-msvc.zip) for windows and run daktilo.exe 
2. Run Daktilo in Windows. 
3. Change the sound output from speakers to headphones. 

 

**Expected behavior**

Sounds should start coming from my headphones, not  remain coming from my speakers. 

 
**Software information**

- Operating system:  Windows 11 Build 22H2
- Rust version: n/a
- Project version: 0.2.0

**Comment by orhun** [comment]
Hello, thanks for reporting this! 🐻 

Not sure if we can support auto-switching output devices on the fly but one thing we can do is support selecting the device for playback.

So in 6bd8269639bd95f5a4386e32f9abc9adf15c12d1 I added this feature:

```sh
$ daktilo --list-devices
# lists the available devices

$ daktilo --device "sysdefault:CARD=Generic_1"
# plays the sound on the selected device
```

I hope this helps!
